### ISSUE TITLE
pre-release: validate new features

### ISSUE THREAD

**Issue by nesnoj** [openego/dingo#169]
We have to validate some new features which were recently implemented:

~~- [ ] Categorisation of MVGD #121~~
- [x] Allocation of generator (REA) to house connections #129 
- [x] YARAB https://github.com/openego/data_processing/issues/87
- [x] Relocation of switch disconnectors #167 
- [x] Correlation between population and peak_load_residential #161 (sql snippets for validation #147)
- [ ] A bunch of the thinks to cross-check or discuss regarding LV grids #133 
  - [ ] analyzing a few grids, over-voltage up to 10% occured only in load case
  - [ ] Impedance seems to be quite high: 30 ... 80 ohm (R and X)
  - [ ] There is a high chance voltage issues or overloading remains for some branches due to `s_max` exceeding capacity of largest cable
(see discussion [here](https://github.com/openego/dingo/commit/51b462340ff0eaa3d44cdd5b534cfcee80fc016a))
  - [ ] (n-1)-criterion is not considered for MV-LV transformers: cross-check with literature
  - [ ] Just a note: Extension of transformers when voltage issues at MV-LV (secondary side) bus bar occur has no effect on voltage level. May voltage issue than is related to impedance of MV grid

**Comment by gplssm** [comment]
Closed in favor of #212
