### ISSUE TITLE
Inspect and validate Dingo data

### ISSUE THREAD

**Issue by gplssm** [openego/dingo#212]
## List of validation steps _(tbc)_

- [ ] Inspect MV and LV grids regarding overloading and overvoltage (based of stats export)
- [ ] Validate loads and feeders #198 
- [ ] Inspect 10kV/20kV grid voltage ratio #121 
- [ ] Allocation of LV generators #111 
- [ ] Deep analysis of MV topology #186

**Comment by jochenbuehler** [comment]
It looks like there is a bug in MVGD 1833. The two marked cable distributers seem to have no purpose

![bug_in_mvgd_1833](https://user-images.githubusercontent.com/28706452/28515500-274a2b56-705e-11e7-8e54-73932702fe48.png)
