### ISSUE TITLE
Add meta description

### ISSUE THREAD

**Issue by gplssm** [openego/dingo#46]
Add a meta description to auto-generated documentation of Dingo that contains
- Methodological approach
- Use cases
- ...

**Comment by gplssm** [comment]
Minimum docs to complete for a first release
- [ ] Welcome page of RTD
- [ ] Readme on GitHub
- [ ] Getting started
  - [ ] Installation instruction (as short as possible)
  - [ ] Provide overview on examples and how to adapt from them

Improvement on API docs is now done in #45 as will probably contained in the next release.

**Comment by gplssm** [comment]
Everything (apart from #130 ) is done. Only "What's new" remains. There two options to fill this section

1. Provide a diff report relative to already released pre-version v0.1.0-pre (hard way)
2. Say that 0.1.0 is the first version and everything is new. No further detailing (easy short-cut way)

@nesnoj what's your preference?

**Comment by nesnoj** [comment]
2.
